[package]
name = "zap-language"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
name = "zap_language"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies.tree-sitter]
version = "0.25"

[dependencies.tree-sitter-zap]
git = "https://github.com/filiptibell/tree-sitter-zap"
rev = "90a8db361fda7f487cdba5d21a816aaad027f2a6"
