id = "zap-language"
name = "Zap Language"
version = "0.1.0"
schema_version = 1
authors = ["Filip Tibell <filip.tibell@example.com>"]
description = "Zap language support for Zed"
repository = "https://github.com/filiptibell/zap-language"

[grammars.zap]
repository = "https://github.com/filiptibell/tree-sitter-zap"
rev = "d6b0b49b59bb779ea12d8d070720b192bf8358dd"

[language_servers.zap-language-server]
name = "Zap Language Server"
languages = ["Zap"]
