[package]
name = "async-lsp-boilerplate"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
name = "async_lsp_boilerplate"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
