[package]
name = "zap-formatter"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
name = "zap_formatter"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
thiserror = "2.0"

zap-language = { path = "../zap-language" }
