name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.value }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from manifest
        id: get_version
        run: |
          PACKAGE_VERSION=$(./scripts/get-version.sh)
          echo "value=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT

  build:
    needs: ["init"]
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            runner-os: windows-latest
            artifact-name: zap-language-server-${{ needs.init.outputs.version }}-windows-x86_64
            cargo-target: x86_64-pc-windows-msvc

          - name: Linux x86_64
            runner-os: ubuntu-latest
            artifact-name: zap-language-server-${{ needs.init.outputs.version }}-linux-x86_64
            cargo-target: x86_64-unknown-linux-gnu

          - name: macOS x86_64
            runner-os: macos-13
            artifact-name: zap-language-server-${{ needs.init.outputs.version }}-macos-x86_64
            cargo-target: x86_64-apple-darwin

          - name: macOS aarch64
            runner-os: macos-14
            artifact-name: zap-language-server-${{ needs.init.outputs.version }}-macos-aarch64
            cargo-target: aarch64-apple-darwin

    name: Build - ${{ matrix.name }}
    runs-on: ${{ matrix.runner-os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.cargo-target }}

      - name: Build binary
        run: |
          cargo build \
          --locked --all-features \
          --release --target ${{ matrix.cargo-target }}

      - name: Create release archive
        run: ./scripts/zip-release.sh ${{ matrix.cargo-target }}

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: release.zip

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ["init", "build"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download releases
        uses: actions/download-artifact@v4
        with:
          path: ./releases

      - name: Unpack releases
        run: ./scripts/unpack-releases.sh "./releases"

      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ needs.init.outputs.version }}
          tag_name: v${{ needs.init.outputs.version }}
          fail_on_unmatched_files: true
          files: ./releases/*.zip
          draft: true
